backtesting:
  enabled: false
  start_date: "2024-12-09"
  end_date: "2024-12-13"
  initial_balance: 1.0
  trade_size: 0.2

trading:
  initial_balance: 10000.0
  trade_size: 2000
  max_positions: 4
  profit_target_1: 0.03
  profit_target_2: 0.007
  cumulative_profit_target: 0.035
  fib_entry_threshold: -0.009
  fib_reset_threshold: 0.01
  max_candle_range: 0.009
  countdown_periods: 64
  require_fib50_cross: true
  lookback_periods: 64

chart_styles:
  fib_0_line:
    color: "#FFFFFF" # Solid White
    dash: "solid"    # Solid line
    width: 2
  fib_50_line:
    color: "#FFFF00" # Dotted Yellow
    dash: "dot"      # Dotted line
    width: 1
  entry_threshold_line:
    color: "#FF0000" # Solid Red
    dash: "solid"    # Solid line
    width: 1
  current_price_line:
    color: "#00FF00" # Lime Green (unchanged from your original request)
    dash: "dot"
    width: 1
  open_position_line:
    color: "#00FFFF" # Cyan (unchanged)
    dash: "dashdot"
    width: 2
  trade_path_win_line:
    color: "#00FF00" # Green (unchanged)
    dash: "dot"
    width: 1
  trade_path_loss_line:
    color: "#FF0000" # Red (unchanged)
    dash: "dot"
    width: 1

paths:
  #historical_data: '../price_data/5min_ohlc_data.csv'
  live_data: 'sol_usdc_price_history_jupiter.csv'
  trade_history: 'trade_history.csv'
  chart_output: 'trading_charts/trading_chart.png'

websocket:
  port: 8765
  host: "0.0.0.0"

  logging:
  level: "INFO"
  file: "trading_bot.log"
